/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/route_utils.py", line 761, in __call__
    await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 123, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 109, in app
    response = await f(request)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 389, in app
    raw_response = await run_endpoint_function(
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 290, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/concurrency.py", line 38, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/routes.py", line 431, in main
    gradio_api_info = api_info(False)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/routes.py", line 460, in api_info
    app.api_info = app.get_blocks().get_api_info()
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/blocks.py", line 2785, in get_api_info
    python_type = client_utils.json_schema_to_python_type(info)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 893, in json_schema_to_python_type
    type_ = _json_schema_to_python_type(schema, schema.get("$defs"))
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 947, in _json_schema_to_python_type
    des = [
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 948, in <listcomp>
    f"{n}: {_json_schema_to_python_type(v, defs)}{get_desc(v)}"
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 955, in _json_schema_to_python_type
    f"str, {_json_schema_to_python_type(schema['additionalProperties'], defs)}"
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 901, in _json_schema_to_python_type
    type_ = get_type(schema)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 863, in get_type
    if "const" in schema:
TypeError: argument of type 'bool' is not iterable
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/route_utils.py", line 761, in __call__
    await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 123, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 109, in app
    response = await f(request)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 389, in app
    raw_response = await run_endpoint_function(
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 290, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/concurrency.py", line 38, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/routes.py", line 431, in main
    gradio_api_info = api_info(False)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/routes.py", line 460, in api_info
    app.api_info = app.get_blocks().get_api_info()
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/blocks.py", line 2785, in get_api_info
    python_type = client_utils.json_schema_to_python_type(info)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 893, in json_schema_to_python_type
    type_ = _json_schema_to_python_type(schema, schema.get("$defs"))
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 947, in _json_schema_to_python_type
    des = [
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 948, in <listcomp>
    f"{n}: {_json_schema_to_python_type(v, defs)}{get_desc(v)}"
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 955, in _json_schema_to_python_type
    f"str, {_json_schema_to_python_type(schema['additionalProperties'], defs)}"
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 901, in _json_schema_to_python_type
    type_ = get_type(schema)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 863, in get_type
    if "const" in schema:
TypeError: argument of type 'bool' is not iterable
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/route_utils.py", line 761, in __call__
    await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 123, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 109, in app
    response = await f(request)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 389, in app
    raw_response = await run_endpoint_function(
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 290, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/concurrency.py", line 38, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/routes.py", line 431, in main
    gradio_api_info = api_info(False)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/routes.py", line 460, in api_info
    app.api_info = app.get_blocks().get_api_info()
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/blocks.py", line 2785, in get_api_info
    python_type = client_utils.json_schema_to_python_type(info)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 893, in json_schema_to_python_type
    type_ = _json_schema_to_python_type(schema, schema.get("$defs"))
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 947, in _json_schema_to_python_type
    des = [
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 948, in <listcomp>
    f"{n}: {_json_schema_to_python_type(v, defs)}{get_desc(v)}"
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 955, in _json_schema_to_python_type
    f"str, {_json_schema_to_python_type(schema['additionalProperties'], defs)}"
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 901, in _json_schema_to_python_type
    type_ = get_type(schema)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 863, in get_type
    if "const" in schema:
TypeError: argument of type 'bool' is not iterable
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/route_utils.py", line 761, in __call__
    await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 123, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 109, in app
    response = await f(request)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 389, in app
    raw_response = await run_endpoint_function(
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 290, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/concurrency.py", line 38, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/routes.py", line 431, in main
    gradio_api_info = api_info(False)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/routes.py", line 460, in api_info
    app.api_info = app.get_blocks().get_api_info()
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/blocks.py", line 2785, in get_api_info
    python_type = client_utils.json_schema_to_python_type(info)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 893, in json_schema_to_python_type
    type_ = _json_schema_to_python_type(schema, schema.get("$defs"))
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 947, in _json_schema_to_python_type
    des = [
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 948, in <listcomp>
    f"{n}: {_json_schema_to_python_type(v, defs)}{get_desc(v)}"
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 955, in _json_schema_to_python_type
    f"str, {_json_schema_to_python_type(schema['additionalProperties'], defs)}"
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 901, in _json_schema_to_python_type
    type_ = get_type(schema)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 863, in get_type
    if "const" in schema:
TypeError: argument of type 'bool' is not iterable
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/route_utils.py", line 761, in __call__
    await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 123, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 109, in app
    response = await f(request)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 389, in app
    raw_response = await run_endpoint_function(
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/fastapi/routing.py", line 290, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/starlette/concurrency.py", line 38, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/routes.py", line 431, in main
    gradio_api_info = api_info(False)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/routes.py", line 460, in api_info
    app.api_info = app.get_blocks().get_api_info()
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/blocks.py", line 2785, in get_api_info
    python_type = client_utils.json_schema_to_python_type(info)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 893, in json_schema_to_python_type
    type_ = _json_schema_to_python_type(schema, schema.get("$defs"))
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 947, in _json_schema_to_python_type
    des = [
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 948, in <listcomp>
    f"{n}: {_json_schema_to_python_type(v, defs)}{get_desc(v)}"
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 955, in _json_schema_to_python_type
    f"str, {_json_schema_to_python_type(schema['additionalProperties'], defs)}"
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 901, in _json_schema_to_python_type
    type_ = get_type(schema)
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio_client/utils.py", line 863, in get_type
    if "const" in schema:
TypeError: argument of type 'bool' is not iterable
🎚️ Starting AI Mixing Engineer...
============================================================
✅ AI Provider: Kimi K2
============================================================
Running on local URL:  http://127.0.0.1:7861
Traceback (most recent call last):
  File "/Users/nr/Documents/GitHub/main/ai_mixing_engineer.py", line 456, in <module>
    app.launch(
  File "/Users/nr/Documents/GitHub/main/venv/lib/python3.9/site-packages/gradio/blocks.py", line 2465, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.
